"""FIT parsing against synthetic files.

Every file here is generated by tests/fixtures/fit_writer.py. Real FIT
files carry real heart rate data and must never enter this repository.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import pytest

from tempo.ingest.errors import FitFileError
from tempo.ingest.fit_parser import (
    MAX_ACTIVITY_SPAN_S,
    fit_activity_id,
    parse_fit_file,
)
from tests.fixtures.fit_writer import (
    SPORT_CYCLING,
    SPORT_FITNESS_EQUIPMENT,
    SPORT_WALKING,
    Sample,
    write_activity_file,
)

START_UTC = dt.datetime(2026, 1, 15, 6, 30, tzinfo=dt.UTC)


def _run(
    tmp_path: Path, samples: list[Sample], name: str = "run.fit", **kwargs: object
) -> Path:
    return write_activity_file(
        tmp_path / name,
        start_utc=START_UTC,
        samples=samples,
        **kwargs,  # type: ignore[arg-type]
    )


def _steady(seconds: int) -> list[Sample]:
    return [
        Sample(offset_s=offset, hr=130 + offset % 10, distance_m=offset * 2.8)
        for offset in range(seconds)
    ]


def test_a_plain_run_parses_into_a_dense_one_hz_grid(tmp_path: Path) -> None:
    path = _run(tmp_path, _steady(10), elapsed_s=9, timer_s=9, distance_m=25.2)

    parsed = parse_fit_file(path)

    assert parsed.sport == "Run"
    assert len(parsed.samples) == 10
    assert [sample.offset_s for sample in parsed.samples] == list(range(10))
    assert parsed.elapsed_s == 9
    assert parsed.moving_s == 9
    assert parsed.distance_m == pytest.approx(25.2)
    assert parsed.avg_hr == 142
    assert parsed.max_hr == 168
    assert parsed.elevation_gain_m == pytest.approx(12.0)
    assert parsed.gap_seconds == 0
    assert parsed.derived_summary is False


def test_coordinates_are_converted_from_semicircles(tmp_path: Path) -> None:
    path = _run(tmp_path, [Sample(offset_s=0, lat=47.07, lon=15.44)])

    sample = parse_fit_file(path).samples[0]

    assert sample.lat == pytest.approx(47.07, abs=1e-6)
    assert sample.lon == pytest.approx(15.44, abs=1e-6)


def test_pace_is_derived_from_distance_and_moving_time(tmp_path: Path) -> None:
    path = _run(tmp_path, _steady(5), distance_m=1000.0, timer_s=300)

    parsed = parse_fit_file(path)

    assert parsed.avg_pace_s_per_km == pytest.approx(300.0)


def test_a_heart_rate_dropout_stays_none(tmp_path: Path) -> None:
    """The channel is missing for that second; the others are not."""
    samples = _steady(6)
    samples[2] = Sample(offset_s=2, hr=None, distance_m=5.6)
    path = _run(tmp_path, samples)

    parsed = parse_fit_file(path)

    assert parsed.samples[2].hr is None
    assert parsed.samples[2].speed_m_s == pytest.approx(2.8)
    assert parsed.samples[1].hr is not None
    assert parsed.samples[3].hr is not None
    # A dropout is not a gap: the second still carries data.
    assert parsed.gap_seconds == 0


def test_a_pause_becomes_empty_samples_and_is_not_interpolated(
    tmp_path: Path,
) -> None:
    """Seconds 3..7 were never recorded, so nothing is drawn across them."""
    samples = [
        Sample(offset_s=offset, hr=140, altitude_m=210.0, distance_m=offset * 2.8)
        for offset in (0, 1, 2, 8, 9)
    ]
    path = _run(tmp_path, samples, elapsed_s=9, timer_s=5)

    parsed = parse_fit_file(path)

    assert len(parsed.samples) == 10
    assert parsed.gap_seconds == 5
    for offset in range(3, 8):
        gap = parsed.samples[offset]
        assert gap.is_empty
        assert gap.hr is None
        assert gap.altitude_m is None
        assert gap.speed_m_s is None
    assert parsed.samples[2].hr == 140
    assert parsed.samples[8].hr == 140


def test_a_run_without_gps_parses(tmp_path: Path) -> None:
    samples = [
        Sample(offset_s=offset, lat=None, lon=None, distance_m=offset * 2.8)
        for offset in range(5)
    ]
    path = _run(tmp_path, samples)

    parsed = parse_fit_file(path)

    assert all(sample.lat is None for sample in parsed.samples)
    assert all(sample.lon is None for sample in parsed.samples)
    assert all(sample.hr is not None for sample in parsed.samples)
    assert parsed.gap_seconds == 0


def test_a_run_without_heart_rate_parses(tmp_path: Path) -> None:
    samples = [Sample(offset_s=offset, hr=None) for offset in range(5)]
    path = _run(tmp_path, samples, avg_hr=None, max_hr=None)

    parsed = parse_fit_file(path)

    assert parsed.avg_hr is None
    assert parsed.max_hr is None
    assert all(sample.hr is None for sample in parsed.samples)
    assert all(sample.speed_m_s is not None for sample in parsed.samples)


def test_without_a_session_message_the_summary_is_derived(tmp_path: Path) -> None:
    samples = [
        Sample(offset_s=offset, hr=140 + offset, distance_m=offset * 3.0)
        for offset in range(5)
    ]
    path = _run(tmp_path, samples, with_session=False)

    parsed = parse_fit_file(path)

    assert parsed.derived_summary is True
    assert parsed.avg_hr == 142
    assert parsed.max_hr == 144
    assert parsed.distance_m == pytest.approx(12.0)
    assert parsed.elapsed_s == 4
    # No session and no ascent field: nothing to report rather than a zero.
    assert parsed.elevation_gain_m is None


def test_a_session_without_heart_rate_is_not_back_filled_from_records(
    tmp_path: Path,
) -> None:
    """The file's own summary wins — the parser does not second-guess it."""
    path = _run(tmp_path, _steady(5), avg_hr=None, max_hr=None)

    parsed = parse_fit_file(path)

    assert parsed.avg_hr is None
    assert parsed.max_hr is None


def test_the_utc_offset_from_the_activity_message_gives_local_time(
    tmp_path: Path,
) -> None:
    path = _run(tmp_path, _steady(3), utc_offset_s=2 * 3600)

    parsed = parse_fit_file(path)

    assert parsed.start_utc == START_UTC
    assert parsed.start_local == dt.datetime(2026, 1, 15, 8, 30)
    assert parsed.start_local.tzinfo is None
    assert parsed.local_time_assumed is False


def test_without_an_activity_message_local_time_is_flagged_as_assumed(
    tmp_path: Path,
) -> None:
    path = _run(tmp_path, _steady(3), with_activity=False)

    parsed = parse_fit_file(path)

    assert parsed.start_local == dt.datetime(2026, 1, 15, 6, 30)
    assert parsed.local_time_assumed is True


def test_laps_are_parsed_with_index_and_pace(tmp_path: Path) -> None:
    path = _run(
        tmp_path,
        _steady(12),
        laps=[(0, 6, 1000.0, 138), (6, 6, 1200.0, 151)],
    )

    parsed = parse_fit_file(path)

    assert [lap.index for lap in parsed.laps] == [0, 1]
    assert parsed.laps[0].distance_m == pytest.approx(1000.0)
    assert parsed.laps[0].duration_s == 6
    assert parsed.laps[0].avg_hr == 138
    assert parsed.laps[0].avg_pace_s_per_km == pytest.approx(6.0)
    assert parsed.laps[1].avg_pace_s_per_km == pytest.approx(5.0)


def test_an_activity_without_laps_yields_no_laps(tmp_path: Path) -> None:
    path = _run(tmp_path, _steady(3))

    assert parse_fit_file(path).laps == ()


def test_the_first_record_of_a_second_wins(tmp_path: Path) -> None:
    """Two records in the same second are not averaged into a third value."""
    path = _run(
        tmp_path,
        [Sample(offset_s=0, hr=120), Sample(offset_s=0, hr=180)],
    )

    parsed = parse_fit_file(path)

    assert len(parsed.samples) == 1
    assert parsed.samples[0].hr == 120


@pytest.mark.parametrize(
    ("sport", "expected"),
    [
        (SPORT_CYCLING, "Ride"),
        (SPORT_WALKING, "Walk"),
        # No category for it, so it is not forced into one.
        (SPORT_FITNESS_EQUIPMENT, "Other"),
    ],
)
def test_the_sport_is_normalised_onto_one_vocabulary(
    tmp_path: Path, sport: int, expected: str
) -> None:
    path = _run(tmp_path, _steady(3), sport=sport)

    assert parse_fit_file(path).sport == expected


def test_a_file_with_no_records_parses_to_an_empty_stream(tmp_path: Path) -> None:
    path = _run(tmp_path, [], elapsed_s=0, timer_s=0)

    parsed = parse_fit_file(path)

    assert parsed.samples == ()
    assert parsed.start_utc == START_UTC


def test_an_absurd_span_is_refused(tmp_path: Path) -> None:
    path = _run(
        tmp_path,
        [Sample(offset_s=0), Sample(offset_s=MAX_ACTIVITY_SPAN_S + 60)],
        elapsed_s=60,
        timer_s=60,
    )

    with pytest.raises(FitFileError, match="beyond the"):
        parse_fit_file(path)


def test_a_corrupt_file_raises_a_fit_file_error(tmp_path: Path) -> None:
    broken = tmp_path / "broken.fit"
    broken.write_bytes(b"this is not a FIT file at all")

    with pytest.raises(FitFileError, match="could not be parsed"):
        parse_fit_file(broken)


def test_a_truncated_file_raises_a_fit_file_error(tmp_path: Path) -> None:
    path = _run(tmp_path, _steady(20))
    truncated = tmp_path / "truncated.fit"
    truncated.write_bytes(path.read_bytes()[:60])

    with pytest.raises(FitFileError):
        parse_fit_file(truncated)


def test_a_missing_file_raises_an_os_error(tmp_path: Path) -> None:
    """A path that is not there is the caller's problem, not a parse error."""
    with pytest.raises(OSError):
        parse_fit_file(tmp_path / "nope.fit")


def test_the_activity_id_is_derived_from_the_file_contents(
    tmp_path: Path,
) -> None:
    first = _run(tmp_path, _steady(5), name="a.fit")
    same = _run(tmp_path, _steady(5), name="b.fit")
    different = _run(tmp_path, _steady(6), name="c.fit")

    assert fit_activity_id(first) == fit_activity_id(same)
    assert fit_activity_id(first) != fit_activity_id(different)
    assert fit_activity_id(first).startswith("fit-")
